dist: xenial
language: perl

#
# Could add this to the cpanfile, but "normally" I dont need it, as I use
# the local Devel::Cover html report.
#
before_script:
  - sudo apt-get update -y
  - which cpanm
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
  - make build_dep

script:
    - make cover || exit
    - cover -report codecov
    - make deb

# TODO:
# - build the minimal test environment
# - ensure that the package can install
# - run some tests within that environment
# - maybe copy the test files into the built package?
